### ISSUE TITLE
sending message with Sender ID

### ISSUE THREAD

**Issue by congpine** [kolypto/py-smsframework-clickatell#1]
Hi there,
Does your framework offer Sender ID?
I can't find it anywhere.
I think , by default clickatel will use their own number as Sender ID.

I have registered 2 sender id, but don't know how to use them in the outgoing sms.

thanks

**Comment by kolypto** [comment]
Hi!

Sure it does support SenderID. Use either `OutgoingMessage.src`:

```python
OutgoingMessage(..., src='123456')
```

or use `provider_options.senderId`:

```python
om = OutgoingMessage(...)
om.options(senderId='My Name')
```
